### PR TITLE
fix(parser): fix lexical analysis on export of async func

### LINKED ISSUE #360: Asynchronous function exports are not working.
When in `module` goal and exporting an async function like so:
```js
export async function hey () {
    // This should work?
}
```
It says: `[3:1]: Cannot export a duplicate name 'hey'`

### PR DESCRIPTION
**Pull request by 3cp**
closes #360

### CODE REVIEW

File: src/parser.ts [hunk 1]
```diff
@@ -3580,10 +3579,6 @@ function parseExportDeclaration(
           tokenLine,
           tokenColumn
         );
-        if (scope) {
-          key = declaration.id ? declaration.id.name : '';
-          declareUnboundVariable(parser, key);
-        }
```
Comment (3cp) [inline src/parser.ts:3586]: parseFunctionDeclaration already does declareUnboundVariable. This is same for non-async function export in previous lines.

**Review by fisker — APPROVED** [review]

**Comment by 3cp** [comment]
Thx!
