### PR TITLE
fix: follow latest decorator proposal

### LINKED ISSUE #105: The class decorators are not correctly positioned in the AST.
The class decorators array is put before the `Class Declaration` element instead of being put as the `decorators` property's value of the `Class Declaration` element.

Here is an example. Given the following JavaScript code:

```javascript
import {MyDecorator} from './decorators.js';
@MyDecorator
class MyViewModel {
}
```

the output AST is:

```javascript
[
  {
    type: 'ImportDeclaration',
    specifiers: [ [Object] ],
    source: {
      type: 'Literal',
      value: './decorators.js',
      start: 26,
      end: 43,
      range: [Array]
    },
    start: 0,
    end: 44,
    range: [ 0, 44 ]
  },
  [
    {
      type: 'Decorator',
      expression: [Object],
      start: 45,
      end: 57,
      range: [Array]
    }
  ],
  {
    type: 'ClassDeclaration',
    id: {
      type: 'Identifier',
      name: 'MyViewModel',
      start: 64,
      end: 75,
      range: [Array]
    },
    superClass: null,
    decorators: [],
    body: { type: 'ClassBody', body: [], start: 76, end: 79, range: [Array] },
    start: 58,
    end: 79,
    range: [ 58, 79 ]
  }
]
```

As you can see the `ClassDeclaration.decorators` property is an empty array. But just before the `ClassDeclaration` object there is an array of decorators.

Removing the lines

```javascript
    case Token.Decorator:
      return parseDecorators(parser, context) as ESTree.Decorator[];
```

from the `parseModuleItem()` function seems to fix the problem.

### PR DESCRIPTION
**Pull request by 3cp**
closes #105

-----
Move to new decorator proposal broke the old code `@dec export class A {}`. Need to improve parseExportDeclaration to support decorator before export keyword.

### CODE REVIEW

**Comment by 3cp** [comment]
Added `leadingDecorators` to ParserState, it briefly saves the leading decorators before "export" or "class".

The leading decorators for "class" is only saved in leadingDecorators if it's a module item.
```js
@a @b class C {} // This uses leadingDecorators in ParserState
(@a @b class C {}) // This doesn't use leadingDecorators in ParserState
```

Before module item is finalised, it checks that `leadingDecorators` is consumed by a class declaration, otherwise report an error.

This implementation supports decorators before or after "export". But it also has a side effect, it accepts `@a export @b class C {}` as valid JS, same as `export @a @b class C {}`. I guess legacy decorator spec allows this, but not exactly sure.

File: src/parser.ts [hunk 1]
```diff
@@ -415,6 +420,16 @@ export function parseModuleItem(
   line: number,
   column: number
 ): any {
+  if (context & Context.OptionsNext) {
+    const decorators = parseDecorators(parser, context);
```
Comment (KFlash) [inline src/parser.ts:424]: If you aim for performance you should inline this into the `parseDecorators` too avoid the length check. Then you could do `let x = 0` before the loop and `x++`; inside the loop and check `if (x !== 0` at the end of the loop. 
Or even faster  ` if(validdecoratorStart) do iteration consume token  `. If no `validdecoratorStart` the loop will not run, so you automatically have an empty array because that's happen outside the `if statement`.

File: src/parser.ts [hunk 2]
```diff
@@ -7906,6 +7932,11 @@ export function parseClassDeclaration(
 
   const decorators: ESTree.Decorator[] = context & Context.OptionsNext ? parseDecorators(parser, context) : [];
 
+  if (parser.leadingDecorators) {
+    decorators.unshift(...parser.leadingDecorators);
```
Comment (KFlash) [inline src/parser.ts:7936]: Why `unshift`? It's slow

**Review by KFlash — APPROVED** [review]

File: src/parser.ts (hunk 2 above)
Comment (3cp) [reply src/parser.ts:7936]: concat?

Comment (KFlash) [reply src/parser.ts:7936]: Push?

https://dev.to/uilicious/javascript-array-push-is-945x-faster-than-array-concat-1oki

File: src/parser.ts (hunk 1 above)
Comment (3cp) [reply src/parser.ts:424]: Currently leadingDecorators only apply to module item.

By refactoring parseDecorators, do you mean also refactor parseClassElementList to use `parser.leadingDecorators` too? If so, probably I should just rename it to `parser.decorators`.

Comment (KFlash) [reply src/parser.ts:424]: I didn't think about that. My suggestion was just how to get the best performance.

Comment (3cp) [reply src/parser.ts:424]: Just tried. Can not use `parser.decorators` for all decorators because of nested `@bar(@foo class B{}) class A {}`.

The check on length here only applies on the syntax error of a module item. I don't think I could push the logic down to parseDecorators.

**Comment by 3cp** [comment]
I did some cleanup.

**Review by KFlash — APPROVED** [review]
