### PR TITLE
fix(parser): fix onToken callback for template and jsx

### LINKED ISSUE #215: Tokens missing in template literals
When parsing this template literal,
```
`${a}b`
```
, there is no token corresponding to `b`.

**Code:**
```js
const meriyah = require("meriyah");

const tokens = [];
const source = "`${a}b`";
const ast = meriyah.parse(source, {
  onToken(type, start, end) {
    tokens.push({
      type,
      value: source.slice(start, end),
      range: [start, end],
    });
  },
});

console.log(tokens);
```

**Actual output:**

```js
[
  { type: 'TemplateLiteral', value: '`${', range: [ 0, 3 ] },
  { type: 'Identifier', value: 'a', range: [ 3, 4 ] },
  { type: 'Punctuator', value: '}', range: [ 4, 5 ] }
]
```

**Expected:**
The `b` part appears somewhere in the tokens.

### LINKED ISSUE #216: Missing tokens for JSXText
When parsing this JSX,
```
<a>123</a>
```
, there is no token corresponding to `123`.

**Code:**
```js
const meriyah = require("meriyah");

const tokens = [];
const source = `<a>123</a>`;
const ast = meriyah.parse(source, {
  jsx:true,
  onToken(type, start, end, loc) {
    tokens.push({
      type,
      value: source.slice(start, end),
      range: [start, end],
    });
  },
});

console.dir(tokens, {depth: null});
```

**Actual output:**

```js
[
  { type: 'Punctuator', value: '<', range: [ 0, 1 ] },
  { type: 'Identifier', value: 'a', range: [ 1, 2 ] },
  { type: 'Punctuator', value: '>', range: [ 2, 3 ] },
  { type: 'Identifier', value: 'a', range: [ 8, 9 ] },
  { type: 'Punctuator', value: '>', range: [ 9, 10 ] }
]
```

**Expected:**
The `123` part appears somewhere in the tokens.

### PR DESCRIPTION
**Pull request by 3cp**
template and jsx scan are special, there are two cases of re-scan current token, add a param replaceLast=false to setToken to cover the two cases.

closes #215, closes #216

### CODE REVIEW

File: src/parser.ts [hunk 1]
```diff
@@ -9095,10 +9119,6 @@ export function parseJSXClosingFragment(
 export function parseJSXChildren(parser: ParserState, context: Context): ESTree.JSXChild[] {
   const children: ESTree.JSXChild[] = [];
   while (parser.getToken() !== Token.JSXClose) {
-    parser.index = parser.tokenPos = parser.startPos;
-    parser.column = parser.colPos = parser.startColumn;
-    parser.line = parser.linePos = parser.startLine;
-    scanJSXToken(parser, context);
```
Comment (3cp) [inline src/parser.ts:9101]: This reset index to startPos can scan last token again. It look weird, and removing it didn't hurt any test!
Maybe a left over junk.

**Review by fisker — APPROVED** [review]
