### PR TITLE
fix(lexer): fix wrong error when using regex flag s together with m or y

### LINKED ISSUE #202: Duplicate regular expression flag
The parser throws an error when using the `s` and `m` flags together in a regular expression. A very simple example that causes the crash is this:
```
import { parse } from 'meriyah';

parse( String.raw`const done = src.replace( /.*/ms, '' );` );
```
This is using version `4.2.0` of `meriyah`. It works fine with either the `s` or `m` flag by themselves or in combination with other flags. They just can't both be used at the same time. Using both at the same time is syntactically and semantically legal and, occasionally useful.

Edited to add error message:
```
file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:181
    throw new ParseError(parser.index, parser.line, parser.column, type, ...params);
          ^

ParseError [SyntaxError]: [1:31]: Duplicate regular expression flag 's'
    at report (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:181:11)
    at scanRegularExpression (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:876:21)
    at scanSingleToken (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:1929:36)
    at nextToken (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:1710:20)
    at parseArguments (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:6502:5)
    at parseMemberOrUpdateExpression (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:6167:30)
    at parseMemberOrUpdateExpression (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:6199:16)
    at parseExpression (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:5803:12)
    at parseVariableDeclaration (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:5349:16)
    at parseVariableDeclarationList (file:///home/.../project/node_modules/meriyah/dist/meriyah.esm.js:5333:19) {
  index: 31,
  line: 1,
  column: 31,
  description: "[1:31]: Duplicate regular expression flag 's'",
  loc: { line: 1, column: 31 }
}
```

### PR DESCRIPTION
**Pull request by 3cp**
closes #202

### CODE REVIEW

File: src/lexer/regexp.ts [hunk 1]
```diff
@@ -59,13 +59,13 @@ export function scanRegularExpression(parser: ParserState, context: Context): To
   const bodyEnd = parser.index - 1;
 
   const enum RegexFlags {
-    Empty = 0b00000,
-    IgnoreCase = 0b00001,
-    Global = 0b00010,
-    Multiline = 0b00100,
-    Unicode = 0b10000,
-    Sticky = 0b01000,
-    DotAll = 0b1100
```
Comment (3cp) [inline src/lexer/regexp.ts:68]: I got no idea why the previous bit-mask for DotAll 0b1100 is an union of Sticky 0b01000 and Multiline 0b00100.
It doesn't make any sense.

**Review by aladdin-add — APPROVED** [review]

**Comment by 3cp** [comment]
Thx.
