### PR TITLE
fix(parser): get/set/from/of are allowed as identifiers

### LINKED ISSUE #376: Parse failure for `await set()` - cannot use "await" as identifier inside an async function
```js
import { parseModule } from "meriyah";

let code = `
let foo = async () => {
    bar();
    await set();
};
`;

const result = parseModule(code);
console.log(result);
```

If I remove the call to `bar()`, or rename `set()` to something else (e.g. `setFn()`), it parses without error.

`meriyah@6.0.5`.

### PR DESCRIPTION
**Pull request by 3cp**
closes #376

### CODE REVIEW

File: src/meriyah.ts [hunk 1]
```diff
@@ -2,7 +2,10 @@ import { Context } from './common';
 import { parseSource, Options } from './parser';
 import * as ESTree from './estree';
 // Current version
-import { version } from '../package.json';
+import { version as pkgVersion } from '../package.json';
+
+// This bypass troublesome package.json in generated d.ts file.
+const version: string = pkgVersion;
```
Comment (giles-v) [inline src/meriyah.ts:8]: I assume this is a fix for #375? Curious why -- the error I got from TypeScript was a failure to resolve the `../package.json` import, which will still happen here. Looks like my report wasn't specific enough.

Comment (3cp) [reply src/meriyah.ts:8]: This lets typescript to skip reference of package.json in generated d.ts file.
```js
import { Options } from './parser';
import * as ESTree from './estree';
declare const version: string;
export declare function parseScript(source: string, options?: Options): ESTree.Program;
export declare function parseModule(source: string, options?: Options): ESTree.Program;
export declare function parse(source: string, options?: Options): ESTree.Program;
export { Options, ESTree, version };
```

**Review by fisker — APPROVED** [review]

**Comment by 3cp** [comment]
v6.0.6 is released.
