### PR TITLE
fix(lexer): fix regexp char class \u{hhhh} which requires the u flag

### LINKED ISSUE #79: Unterminated regular expression
Found a bug on regexp when parsing latest [svelte](https://github.com/sveltejs/svelte).
Here is the minimum code that triggers the issue:
```js
var a = /[\u{FDD0}-\u{FDEF}]/u;
```
That unicode range troubled meriyah. Seafox also failed.

Use following script to show the Error:
```js
const {parse} = require('meriyah');
const code = `var a = /[\\u{FDD0}-\\u{FDEF}]/u;`;
const ast = parse(code);
```

Error output:
```
/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:188
      throw new ParseError(parser.index, parser.line, parser.column, type, ...params);
      ^

ParseError [SyntaxError]: [1:29]: Unterminated regular expression
    at report (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:188:13)
    at validate (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:2006:11)
    at scanRegularExpression (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:1998:27)
    at scanSingleToken (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:531:38)
    at nextToken (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:359:22)
    at parseVariableDeclaration (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:3080:11)
    at parseVariableDeclarationList (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:3065:21)
    at parseVariableStatement (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:3055:28)
    at parseStatement (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:2607:22)
    at parseStatementListItem (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:2601:22) {
  index: 29,
  line: 1,
  column: 29,
  description: '[1:29]: Unterminated regular expression',
  loc: { line: 1, column: 29 }
}
```

### PR DESCRIPTION
**Pull request by 3cp**
closes #79

-----
As I said in #79 I don't understand the existing double passes. Suggest to not merge before we understand what existing implementation was trying to do.

### CODE REVIEW

**Comment by 3cp** [comment]
Looks like there is some unit tests outside of `test/lexer/regexp.ts` to cover the existing implementation.

**Comment by 3cp** [comment]
Tests are cleaned up.

File: src/lexer/regexp.ts [hunk 1]
```diff
@@ -134,15 +134,9 @@ export function scanRegularExpression(parser: ParserState, context: Context): To
...
-    RegExp(pattern);
-  } catch (e) {
-    report(parser, Errors.UnterminatedRegExp);
-  }
-
   try {
     return new RegExp(pattern, flags);
   } catch (e) {
-    return null;
+    report(parser, Errors.UnterminatedRegExp);
```
Comment (3cp) [inline src/lexer/regexp.ts:140]: The previous double passes might be a patch to cater those generated test code from the JS Fuzzer. But those generated code was invalid anyway.
