### PR TITLE
fix(parser): add missing import-attributes support in ExportNamedDeclaration

### LINKED ISSUE #289: Question about exporting json module
```js
export { default as a } from "foo.json" with { type: "json" };
```

is this valid?

### PR DESCRIPTION
**Pull request by 3cp**
closes #289

### CODE REVIEW

**Comment by 3cp** [comment]
cc @aralroca

File: test/parser/next/import-attributes.ts [hunk 1]
```diff
@@ -43,7 +44,15 @@ describe('Next - Import Attributes', () => {
...
     `(async function () { return import('./2nd-param_FIXTURE.js', await undefined);}())`,
     `var iter = function*() { beforeCount += 1, import('', yield), afterCount += 1;}();`,
-    `var promise; for (promise = import('./2nd-param_FIXTURE.js', 'test262' in {} || undefined); false; );`
+    `var promise; for (promise = import('./2nd-param_FIXTURE.js', 'test262' in {} || undefined); false; );`,
+    `export {default as viaStaticImport2} from './json-idempotency_FIXTURE.json' with { type: 'json' };`,
+    `export {default as viaStaticImport2} from './json-idempotency_FIXTURE.json' with { "type": 'json' };`,
+    `export * as foo from './foo.json' with { "type": 'json' };`,
+    // TODO: to follow up with spec
+    // Current JSON modules spec didn't prevent following line.
+    `export * from './foo.json' with { "type": 'json' };`,
```
Comment (3cp) [inline test/parser/next/import-attributes.ts:53]: I am not exactly sure about this one.

**Review by fisker — APPROVED** [review]
Thank you!
