### PR TITLE
fix(parser): fix jsx parsing on '< / >'

### LINKED ISSUE #185: JSX with comments not correctly parsed
Examples:

```jsx
<a><// line
/a>;
```

```jsx
<a></* block */
/a>;
```

```jsx
</* open fragment */>
</ /* close fragment */>;
```

### PR DESCRIPTION
**Pull request by 3cp**
closes #185

This is better I think. Previous fix will take "< /* xx */ /" as one token, that doesn't make sense, now it's "<" and "/" two tokens.

### CODE REVIEW

File: src/common.ts [hunk 1]
```diff
@@ -393,7 +393,7 @@ export function validateBindingIdentifier(
   // The BoundNames of LexicalDeclaration and ForDeclaration must not
   // contain 'let'. (CatchParameter is the only lexical binding form
   // without this restriction.)
-  if (kind & (BindingKind.Let | BindingKind.Const) && (t & Token.LetKeyword) === Token.LetKeyword) {
+  if (kind & (BindingKind.Let | BindingKind.Const) && (t & Token.Type) === (Token.LetKeyword & Token.Type)) {
```
Comment (3cp) [inline src/common.ts:396]: It was a bug made it very sensitive with the value behind Token.LetKeyword. There are two more same fixes in parser.ts.

Note tsc will replace `(Token.LetKeyword & Token.Type)` with single number, so that should not be an issue.

File: src/lexer/jsx.ts [hunk 2]
```diff
@@ -47,109 +48,65 @@ export function scanJSXString(parser: ParserState, context: Context): Token {
 }
 
 /**
- * Scans JSX token
+ * consume Token.LessThan, Token.LeftBrace, or Token.JSXText
```
Comment (3cp) [inline src/lexer/jsx.ts:51]: Only handle 3 cases, nothing else.

File: src/lexer/scan.ts [hunk 3]
```diff
@@ -297,18 +297,6 @@ export function scanSingleToken(parser: ParserState, context: Context, state: Le
...
-              const index = parser.index + 1;
-
-              // Check that it's not a comment start.
-              if (index < parser.end) {
-                ch = source.charCodeAt(index);
-                if (ch === Chars.Asterisk || ch === Chars.Slash) return Token.LessThan;
-              }
-              advanceChar(parser);
-              return Token.JSXClose;
-            }
```
Comment (3cp) [inline src/lexer/scan.ts:311]: No more JSXClose.

File: src/token.ts [hunk 4]
```diff
@@ -62,142 +62,140 @@ export const enum Token {
   QuestionMark = 22, // ?
   SingleQuote  = 23, // '
   DoubleQuote  = 24, // "
-  JSXClose     = 25, // </
-  JSXAutoClose = 26, // />
```
Comment (3cp) [inline src/token.ts:65]: Removed two tokens def.

File: test/parser/miscellaneous/onToken.ts [hunk 5]
```diff
@@ -220,9 +224,35 @@ describe('Miscellaneous - onToken', () => {
       { token: 'Punctuator', start: 0, end: 1, value: '<' },
       { token: 'Identifier', start: 2, end: 3, value: 'a' },
       { token: 'Punctuator', start: 3, end: 4, value: '>' },
-      { token: 'Punctuator', start: 4, end: 7, value: '< /' },
+      { token: 'Punctuator', start: 4, end: 5, value: '<' },
+      { token: 'Punctuator', start: 6, end: 7, value: '/' },
```
Comment (3cp) [inline test/parser/miscellaneous/onToken.ts:228]: The separate tokens make more sense.

**Review by fisker — APPROVED** [review]
Looks like a lot of work, thank you!
